server:
  port: 8082

spring:
  application:
    name: snippet-runner-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI:https://dev-o02i7bmya113pn5u.us.auth0.com/}
          audiences: ${AUTH0_AUDIENCE:https://snippet-searcher.ingsis/}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
